version: '3'
services:
  db:

    platform: linux/amd64
    image: mysql:8.0.33
    #image: mysql/mysql-server:latest

    # platform: linux/amd64

    restart: always

    # 環境変数を設定
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
        #- MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

    # ホスト側のポート:コンテナのポート
    ports:
      - '3306:3306'

    # ボリュームバインド
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./db/logs:/var/log/mysql

    #使用するネットワーク
    networks:
      - backend

  api:
    image: node:20

    restart: always

    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=${TZ}
      #ホットリロードを有効に
      - CHOKIDAR_USEPOLLING=true

    ports:
      - '3000:3000'
      - '5555:5555'

    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./apiをコンテナの/appにマウント）
    volumes:
      - ./api:/api

    # 起動時のカレントフォルダを指定
    working_dir: /api

    # 起動後に実行するコマンドを指定
    # command:
    #   npm install

    #コンテナを起動させ続けるよう設定
    tty: true
    stdin_open: true

    networks:
      - backend

    #依存関係（apiコンテナより先にdbコンテナが起動するように設定）
    depends_on:
      - db

  app:
    image: node:20

    restart: always

    environment:
      - CHOKIDAR_USEPOLLING=true

    ports:
      - '8080:8080'

    volumes:
      - ./app:/app

    working_dir: /app

    # command:
    #   npm install

    #コンテナを起動させ続けるよう設定
    tty: true
    stdin_open: true

    networks:
      - backend

    depends_on:
      - api

networks:
  backend:

volumes:
  mysqldata:
